image: '${DOCKER_REG}/ops/ubuntu:18.04'

# SONAR_PROJECT，格式：产品-项目-分支，这里变量是前缀`产品`
# 产品：sec、fin、industry、homepage，如为空，则填充`default`
# DST_DIR: 目标服务器代码目录
variables:
  SONAR_PROJECT: 'fe-rsc'
  DST_HOST_PORT: 2822
  DST_HOSTS: '192.168.5.2 192.168.5.3 192.168.5.15 192.168.5.14 192.168.5.4 172.16.3.199'
  DST_DIR: '/opt/rsc1.3/fe'
  NPM_REG: 'https://registry.npm.taobao.org'

# 目前只区分分支：`线上`和`其他`
# `线上`：需要手动执行代码检测
# `其他`：代码提交后，自动执行

before_script:
  - source .gitlab/scripts/utils.sh
stages:
  - '代码质量检测'
  - '代码构建'
  - '代码部署'

include:
  - local: '.gitlab/ci/job-codecheck-online.yml'
  - local: '.gitlab/ci/job-codecheck-test.yml'
  - local: '.gitlab/ci/job-code-deploy-test.yml'
  - local: '.gitlab/ci/job-code-deploy-online.yml'
