export const PERMISSION_LIST = [
  {
    key: 'dataManage',
    title: '数据中心',
    children: [
      {
        key: 'ownData',
        title: '我的数据',
        uiPermissions: ['ownDataCreate', 'ownDetail', 'ownDataAuth', 'ownDataDel'],
      },
      {
        key: 'authorizeData',
        title: '合作数据',
        uiPermissions: ['authorizeDataAuth'],
      },
      {
        key: 'dataConnect',
        title: '数据连接',
        uiPermissions: [],
      },
      // {
      //   key: 'ownDetail',
      //   title: '数据详情',
      //   uiPermissions: [],
      // },
    ],
    uiPermissions: [],
  },
  {
    key: 'projectCenter',
    title: '项目中心',
    children: [
      {
        key: 'projectList',
        title: '项目列表',
        children: [
          {
            key: 'dataGet',
            title: '数据获取',
            uiPermissions: ['dataGetDetail', 'dataGetCrete', 'dataGetDel'],
            children: [
              // {
              //   key: 'dataGetDetail',
              //   title: '数据详情',
              //   uiPermissions: [],
              // },
              {
                key: 'dataAlign',
                title: '对齐数据',
                uiPermissions: ['featureDealCreate', 'featureDealDel'],
              },
              {
                key: 'featureProject',
                title: '特征工程',
                uiPermissions: [
                  'featureProjectCreate',
                  'featureProjectEdit',
                  'featureProjectDel',
                  'featureProjectDetail',
                ],
              },
            ],
          },
          {
            key: 'jointModeling',
            title: '联合建模',
            uiPermissions: ['jointModelingCreate', 'jointModelingDetail'],
          },
          {
            key: 'eventList',
            title: '任务列表',
            uiPermissions: ['eventDetail'],
          },
          {
            key: 'serviceManager',
            title: '服务管理',
            uiPermissions: [],
            children: [
              {
                key: 'offline',
                title: '离线跑批',
                uiPermissions: ['offlineCreate'],
              },
              {
                key: 'serviceOnline',
                title: '在线服务',
                uiPermissions: ['serviceOnlineCreate', 'onlineDetail'],
              },
            ],
          },
        ],
        uiPermissions: ['projectCreate', 'projectEdit', 'projectDel'],
      },
    ],
    uiPermissions: [],
  },
  // {
  //   key: 'setting',
  //   title: '管理控制台',
  //   children: [
  //     {
  //       key: 'userManage',
  //       title: '用户管理',
  //       uiPermissions: ['userManageCreate', 'userManageEdit'],
  //     },
  //     {
  //       key: 'authoritiesRole',
  //       title: '权限角色管理',
  //       uiPermissions: ['authoritiesRoleCreate', 'authoritiesRoleEdit'],
  //     },
  //     {
  //       key: 'auditActionManagement',
  //       title: '行为日志',
  //       uiPermissions: [],
  //     },
  //     {
  //       key: 'companyManage',
  //       title: '机构管理',
  //       uiPermissions: ['companyManageDetail'],
  //     },
  //   ],
  //   uiPermissions: [],
  // },
];
export const ALL_AUTHORITIES = {
  menu: [
    'projectCenter',
    'projectList',
    'dataGet',
    'jointModeling',
    'eventList',
    'serviceManager',
    'dataAlign',
    'featureProject',
    'offline',
    'serviceOnline',
    'authorizeData',
    'dataConnect',
    'ownData',
  ],
  checkedPermissions: [
    'dataGetDetail',
    'dataGetCrete',
    'dataGetDel',
    'ownDataCreate',
    'ownDetail',
    'ownDataAuth',
    'ownDataDel',
    'authorizeDataAuth',
    'projectCreate',
    'projectEdit',
    'projectDel',
    'featureDealCreate',
    'featureDealDel',
    'featureProjectCreate',
    'featureProjectEdit',
    'featureProjectDel',
    'featureProjectDetail',
    'jointModelingCreate',
    'jointModelingDetail',
    'eventDetail',
    'offlineCreate',
    'serviceOnlineCreate',
    'onlineDetail',
  ],
};

export const PERMISSION_LIST_MAP = {
  dataManage: '数据中心',
  ownData: '我的数据',
  authorizeData: '合作数据',
  dataConnect: '数据连接',
  projectCenter: '项目中心',
  projectList: '项目列表',
  dataGet: '数据获取',
  dataAlign: '对齐数据',
  featureProject: '特征工程',
  jointModeling: '联合建模',
  eventList: '任务列表',
  serviceManager: '服务管理',
  offline: '离线跑批',
  serviceOnline: '在线服务',
  companyManage: '机构管理',
  auditManagement: '审计管理',
  auditActionManagement: '行为日志',
  setting: '管理控制台',
  userManage: '用户管理',
  authoritiesRole: '权限角色管理',
  ownDataCreate: '添加数据',
  ownDetail: '数据详情',
  ownDataAuth: '授权',
  authorizeDataAuth: '授权',
  projectCreate: '创建项目',
  projectEdit: '项目设置',
  projectDel: '项目删除',
  ownDataDel: '删除',
  dataGetCrete: '添加数据',
  dataGetDetail: '数据详情',
  dataGetDel: '移除',
  featureDealCreate: '创建隐私对齐',
  featureDealDel: '删除',
  featureProjectCreate: '新建',
  featureProjectEdit: '编辑',
  featureProjectDel: '删除',
  featureProjectDetail: '详情',
  jointModelingCreate: '创建模型训练',
  jointModelingDetail: '模型详情',
  eventDetail: '任务列表详情',
  onlineDetail: '在线服务详情',
  offlineCreate: '创建离线跑批',
  serviceOnlineCreate: '创建在线服务',
  companyManageDetail: '机构详情',
  userManageCreate: '新建用户',
  userManageEdit: '编辑用户',
  authoritiesRoleCreate: '新建角色',
  authoritiesRoleEdit: '编辑角色',
};

// export const DEFAULT_CHECKED_PERMISSIONS = ['ownDataAuth', 'ownDataDel', 'ownDataCreate', 'authorizeDataAuth', 'projectCreate', 'projectEdit', 'projectDel', 'dataGetDetail', 'dataGetCrete', 'dataGetDel', 'featureDealCreate', 'featureDealDel', 'featureProjectCreate', 'featureProjectEdit', 'featureProjectDel', 'featureProjectDetail', 'jointModelingCreate', 'jointModelingDetail', 'eventDetail', 'offlineCreate', 'serviceOnlineCreate', 'onlineDetail']
